#!/usr/bin/env bash
_dothis() {
	HISTFILE=~/.bash_history
	set -o history

	((${#COMP_WORDS[@]} != 2)) && return
	IFS=$'\n' read -r -d '' -a suggestions <<< "$(
		history 10 | sed "s|^ ||" | grep "^${COMP_WORDS[1]}"
	)"
	if ((${#suggestions[@]} == 1)); then
		COMPREPLY=("${suggestions[0]#[0-9]* }")
	else
		COMPREPLY=("${suggestions[@]}")
	fi
}

complete -F _dothis dothis
