#!/usr/bin/env bash
# A general, all-purpose extraction script.
#
# Default behavior: Extract archive into given directory
#
# Slightly changed version for use with akyuro

archive="$(readlink -f "$1")"

cd "$2" || exit 1
[ -z "$archive" ] && exit 1

if [ -f "$archive" ] ; then
	case "$archive" in
		*.tar.bz2|*.tbz2) tar xvjf "$archive" ;;
		*.tar.xz) tar xvJf "$archive" ;;
		*.tar.gz|*.tgz) tar xvzf "$archive" ;;
		*.tar.zst|*.tzst) tar xv --zstd -f "$archive" || zstd -c -d "$archive" | tar x ;;
		*.zst) zstd -d "$archive" ;;
		*.lzma) unlzma "$archive" ;;
		*.bz2) bunzip2 "$archive" ;;
		*.rar) unrar x -ad "$archive" ;;
		*.gz) gunzip "$archive" ;;
		*.tar) tar xvf "$archive" ;;
		*.zip) unzip "$archive" ;;
		*.Z) uncompress "$archive" ;;
		*.7z) 7z x "$archive" ;;
		*.xz) unxz "$archive" ;;
		*) exit 1 ;;
	esac
else
	exit 1
fi
