#!/usr/bin/env bash

# field_ix1 separator command args stdin:fields stdout:replaced
on_field() {
	local ix=0 target_ix="$1" sep="$2" cmd="$3"
	shift; shift; shift
	while read -r line; do
		echo -n "$line" | while read -d "$sep" -r field; do
			((ix=ix+1))
			if [ "$ix" == "$target_ix" ]; then
				echo -n "$field" | "$cmd" "$@"
			else
				echo -n "$field"
			fi
			echo -n "$sep"
		done
		echo
	done
}

# number_of_lines new_separators stdin:lines stdout:result
join_n_lines() {
	local lines=() result=() resultIx=0 linesTaken=0
	IFS=$'\n' read -r -d '' -a lines
	for i in "${lines[@]}"; do
		result[$resultIx]="${result[resultIx]}$i$2"
		((linesTaken=linesTaken+1))
		[ "$linesTaken" == "$1" ] &&
			linesTaken=0 &&
			echo "${result[resultIx]}" &&
			((resultIx=resultIx+1))
	done
}
