#include <stdio.h>

enum ansi_seq {
	RESET,

	FG, BG,
	FGRGB, BGRGB,

	BOLD, FAINT, ITALIC, UNDERLINE,
	BLINKING, HIGHLIGHTED, HIDDEN, STRIKETHROUGH,

	MOVE, HOME,
	UP, DOWN, LEFT, RIGHT,
	SAVE, RESTORE,

	ERASEEND, ERASESTART, ERASE,
	ERASEBOTTOM, ERASETOP, CLEAR,

	LI_ON, LI_OFF,
	LI_HORI, LI_VERT,
	LI_UL, LI_DL, LI_DR, LI_UR,
	LI_UDR, LI_UDL, LI_ULR, LI_DLR,
	LI_CROSS, LI_SHADE
};
